#exception
#Name error exception

print(x)